SAT.UI.MVC/Controllers/StudentStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;

namespace SAT.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StudentStatusController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: StudentStatus
        public ActionResult Index()
        {
            return View(db.StudentStatuses.ToList());
        }

        // GET: StudentStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SSID,SSName,SSDescription")] StudentStatus studentStatus)
        {
            if (ModelState.IsValid)
            {
                db.StudentStatuses.Add(studentStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentStatus);
        }

        // GET: StudentStatus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // POST: StudentStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SSID,SSName,SSDescription")] StudentStatus studentStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studentStatus);
        }

        // GET: StudentStatus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            if (studentStatus == null)
            {
                return HttpNotFound();
            }
            return View(studentStatus);
        }

        // POST: StudentStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentStatus studentStatus = db.StudentStatuses.Find(id);
            db.StudentStatuses.Remove(studentStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;
using SAT.UI.MVC.Utilities;

namespace SAT.UI.MVC.Controllers
{
    public class StudentsController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: Students
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Index()
        {
            var students = db.Students.Include(s => s.StudentStatus);
            return View(students.ToList());
        }

        // GET: Students/Details/5
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.SSID = new SelectList(db.StudentStatuses, "SSID", "SSName");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "StudentId,FirstName,LastName,Major,Address,City,State,ZipCode,Phone,Email,PhotoUrl,SSID")] Student student, HttpPostedFileBase studentImage)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                string file = "NoImage.png";
                if (studentImage != null)
                {
                    file = studentImage.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    //check that the uploaded file ext is in our list of good file extensions
                    if (goodExts.Contains(ext))
                    {
                        //if valid ext, check file size <= 4mb (max by default from ASP.NET)
                        if (studentImage.ContentLength <= 4194304)
                        {
                            //create a new file name using a guid
                            //file = Guid.NewGuid() + ext;

                            #region Resize Image
                            string savePath = Server.MapPath("~/Content/img/studentimages/");
                            Image convertedImage = Image.FromStream(studentImage.InputStream);
                            int maxImageSize = 500;
                            int maxThumbSize = 100;
                            ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                            #endregion
                        }
                    }
                }
                student.PhotoUrl = file;
                #endregion
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SSID = new SelectList(db.StudentStatuses, "SSID", "SSName", student.SSID);
            return View(student);
        }

        // GET: Students/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            ViewBag.SSID = new SelectList(db.StudentStatuses, "SSID", "SSName", student.SSID);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "StudentId,FirstName,LastName,Major,Address,City,State,ZipCode,Phone,Email,PhotoUrl,SSID")] Student student, HttpPostedFileBase studentImage)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                if (studentImage != null)
                {
                    string file = studentImage.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    //check that the uploaded file ext is in our list of good file extensions
                    if (goodExts.Contains(ext))
                    {
                        //if valid ext, check file size <= 4mb (max by default from ASP.NET)
                        if (studentImage.ContentLength <= 4194304)
                        {
                            //create a new file name using a guid
                            //file = Guid.NewGuid() + ext;

                            #region Resize Image
                            string savePath = Server.MapPath("~/Content/img/studentimages/");
                            Image convertedImage = Image.FromStream(studentImage.InputStream);
                            int maxImageSize = 500;
                            int maxThumbSize = 100;
                            ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                            #endregion

                            if (student.PhotoUrl != null && student.PhotoUrl != "NoImage.png")
                            {
                                string path = Server.MapPath("~/Content/img/studentimages/");
                                ImageService.Delete(path, student.PhotoUrl);
                            }
                        }
                    }
                    student.PhotoUrl = file;
                }
                #endregion
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SSID = new SelectList(db.StudentStatuses, "SSID", "SSName", student.SSID);
            return View(student);
        }

        // GET: Students/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);

            //Delete the image file of the record that is being removed
            string path = Server.MapPath("~/Content/img/studentimages/");
            ImageService.Delete(path, student.PhotoUrl);

            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Views/StudentStatus/Create.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Add Student Status";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_group"></i><a href="@Url.Action("Index", "Students")">Students</a></li>
            <li><i class="icon_id-2_alt"></i><a href="@Url.Action("Index", "StudentStatus")">Student Statuses</a></li>
            <li><i class="icon_id_alt"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SSName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAT.UI.MVC/Views/StudentStatus/Delete.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Delete Student Status";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_group"></i><a href="@Url.Action("Index", "Students")">Students</a></li>
            <li><i class="icon_id-2_alt"></i><a href="@Url.Action("Index", "StudentStatus")">Student Statuses</a></li>
            <li><i class="icon_id_alt"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<div>
    <h3><strong>Are you sure you want to delete this?</strong></h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SSName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SAT.UI.MVC/Views/StudentStatus/Details.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Student Status Details";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_group"></i><a href="@Url.Action("Index", "Students")">Students</a></li>
            <li><i class="icon_id-2_alt"></i><a href="@Url.Action("Index", "StudentStatus")">Student Statuses</a></li>
            <li><i class="icon_id_alt"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SSName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SSDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SSDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SSID }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SAT.UI.MVC/Views/StudentStatus/Edit.cshtml
@model SAT.DATA.EF.StudentStatus

@{
    ViewBag.Title = "Edit Student Status";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_group"></i><a href="@Url.Action("Index", "Students")">Students</a></li>
            <li><i class="icon_id-2_alt"></i><a href="@Url.Action("Index", "StudentStatus")">Student Statuses</a></li>
            <li><i class="icon_id_alt"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SSID)

        <div class="form-group">
            @Html.LabelFor(model => model.SSName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SSDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SSDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SSDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAT.UI.MVC/Views/StudentStatus/Index.cshtml
@model IEnumerable<SAT.DATA.EF.StudentStatus>

@{
    ViewBag.Title = "Student Statuses";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_group"></i><a href="@Url.Action("Index", "Students")">Students</a></li>
            <li><i class="icon_id-2_alt"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<p>
    <a class="btn btn-info" href="@Url.Action("Create")"><i class="icon_plus_alt2"></i></a>
</p>
<table class="table data-table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SSName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SSDescription)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.SSName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SSDescription)
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-primary" href="@Url.Action("Edit", new { id = item.SSID })"><i class="icon_pencil"></i></a>
                        <a class="btn btn-success" href="@Url.Action("Details", new { id = item.SSID })"><i class="icon_search"></i></a>
                        <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.SSID })"><i class="icon_trash_alt"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $('.data-table').DataTable();
        });
    </script>
}