SAT.UI.MVC/Controllers/ScheduledClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAT.DATA.EF;

namespace SAT.UI.MVC.Controllers
{
    public class ScheduledClassesController : Controller
    {
        private SATEntities db = new SATEntities();

        // GET: ScheduledClasses
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Index()
        {
            var scheduledClasses = db.ScheduledClasses.Include(s => s.Courses).Include(s => s.ScheduledClassStatus);
            return View(scheduledClasses.ToList());
        }

        // GET: ScheduledClasses/Details/5
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            return View(scheduledClass);
        }

        // GET: ScheduledClasses/Create
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName");
            return View();
        }

        // POST: ScheduledClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Create([Bind(Include = "ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,SCSID")] ScheduledClass scheduledClass)
        {
            if (ModelState.IsValid)
            {
                db.ScheduledClasses.Add(scheduledClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // GET: ScheduledClasses/Edit/5
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Scheduling")]
        public ActionResult Edit([Bind(Include = "ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,SCSID")] ScheduledClass scheduledClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduledClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", scheduledClass.CourseId);
            ViewBag.SCSID = new SelectList(db.ScheduledClassStatuses, "SCSID", "SCSName", scheduledClass.SCSID);
            return View(scheduledClass);
        }

        // GET: ScheduledClasses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            if (scheduledClass == null)
            {
                return HttpNotFound();
            }
            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            ScheduledClass scheduledClass = db.ScheduledClasses.Find(id);
            db.ScheduledClasses.Remove(scheduledClass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAT.UI.MVC/Views/ScheduledClasses/Create.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Add Scheduled Class";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_calendar"></i><a href="@Url.Action("Index", "ScheduledClasses")">Scheduled Classes</a></li>
            <li><i class="icon_calendar"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstructorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstructorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SCSID, "SCSID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SCSID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SCSID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAT.UI.MVC/Views/ScheduledClasses/Delete.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Delete Scheduled Class";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_calendar"></i><a href="@Url.Action("Index", "ScheduledClasses")">Scheduled Classes</a></li>
            <li><i class="icon_calendar"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<div>
    <h3><strong>Are you sure you want to delete this?</strong></h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstructorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstructorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Courses.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Courses.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScheduledClassStatus.SCSName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScheduledClassStatus.SCSName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SAT.UI.MVC/Views/ScheduledClasses/Details.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Scheduled Class Details";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_calendar"></i><a href="@Url.Action("Index", "ScheduledClasses")">Scheduled Classes</a></li>
            <li><i class="icon_calendar"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InstructorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InstructorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Courses.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Courses.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ScheduledClassStatus.SCSName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ScheduledClassStatus.SCSName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ScheduledClassId }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SAT.UI.MVC/Views/ScheduledClasses/Edit.cshtml
@model SAT.DATA.EF.ScheduledClass

@{
    ViewBag.Title = "Edit Scheduled Class";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_calendar"></i><a href="@Url.Action("Index", "ScheduledClasses")">Scheduled Classes</a></li>
            <li><i class="icon_calendar"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ScheduledClassId)

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InstructorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InstructorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InstructorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SCSID, "SCSID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SCSID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SCSID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SAT.UI.MVC/Views/ScheduledClasses/Index.cshtml
@model IEnumerable<SAT.DATA.EF.ScheduledClass>

@{
    ViewBag.Title = "Scheduled Classes";
}

<!--overview start-->
<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb page-header">
            <li><i class="icon_house_alt"></i><a href="@Url.Action("Index", "Home")">Dashboard</a></li>
            <li><i class="icon_calendar"></i>@ViewBag.Title</li>
        </ol>
    </div>
</div>

<p>
    <a class="btn btn-info" href="@Url.Action("Create")"><i class="icon_plus_alt2"></i></a>
</p>
<table class="table data-table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InstructorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Courses.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ScheduledClassStatus.SCSName)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstructorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Courses.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScheduledClassStatus.SCSName)
                </td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-primary" href="@Url.Action("Edit", new { id = item.ScheduledClassId })"><i class="icon_pencil"></i></a>
                        <a class="btn btn-success" href="@Url.Action("Details", new { id = item.ScheduledClassId })"><i class="icon_search"></i></a>
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.ScheduledClassId })"><i class="icon_trash_alt"></i></a>
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $('.data-table').DataTable();
        });
    </script>
}